version: '3.9'

services:
  static_server:
    build:
      context: ./static_server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./static_server/static_template:/usr/share/nginx/html:ro
      - ./static_server/nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
