networks:
  biasbinder_network:
    driver: bridge

volumes:
  db_data:

services:
  ###################################################################
  # BASE DE DONNÉES PostgreSQL
  ###################################################################
  db:
    build:
      context: ./project-fehlmann_halimi_stelcher
      dockerfile: Dockerfile
    container_name: biasbinder_db_container
    environment:
      - POSTGRESQL_USERNAME=biasbinder_dev
      - POSTGRESQL_PASSWORD=biasbinder
      - POSTGRESQL_DATABASE=biasbinder_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - biasbinder_network

  ###################################################################
  # API (Spring Boot + Javalin) - Reverse-proxifiée par Traefik + DB
  ###################################################################
  api:
    build:
      context: ./app-dai
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/biasbinder_db?currentSchema=biasbinder_bst
      - SPRING_DATASOURCE_USERNAME=biasbinder_dev
      - SPRING_DATASOURCE_PASSWORD=biasbinder
    expose:
      - "7070"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - biasbinder_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=7070"
      - "traefik.http.routers.api.priority=2"
      - "traefik.http.services.api.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.api.loadBalancer.sticky.cookie.name=api-session"

    deploy:
      replicas: 2

  ###################################################################
  # FRONTEND (React) - direct sur 5173
  ###################################################################
  frontend:
    build:
      context: ./biasfinder-frontend
      dockerfile: Dockerfile
    container_name: biasbinder_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - biasbinder_network

  ###################################################################
  # SERVEUR STATIQUE (Nginx) - route "/" via Traefik
  ###################################################################
  static_server:
    deploy:
      replicas: 3
    build:
      context: ./static_server
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - biasbinder_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=PathPrefix(`/`)"
      - "traefik.http.routers.static.entrypoints=web"
      - "traefik.http.services.static.loadbalancer.server.port=80"
      - "traefik.http.routers.static.priority=1"

  ###################################################################
  # TRAEFIK (Reverse Proxy pour / et /api)
  ###################################################################
  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - biasbinder_network
    labels:
      - "traefik.enable=true"
