version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: development
    user: "root"  # Execute the container as root
